# Generated by Django 3.0.3 on 2021-03-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
