# Generated by Django 3.1.6 on 2021-03-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0004_auto_20210309_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='address',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='city',
            field=models.CharField(default='logan', max_length=200),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renter1', to='genie.user'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='streetAddress',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='zip',
            field=models.CharField(default='84321', max_length=200),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to='genie.user'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
