# Generated by Django 3.1.6 on 2021-03-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0005_auto_20210315_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentOwner', to='genie.user'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentRenter', to='genie.user'),
        ),
    ]
