# Generated by Django 3.1.6 on 2021-03-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0006_auto_20210315_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='owner',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='owner',
            field=models.ManyToManyField(related_name='currentOwner', to='genie.User'),
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='renter',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='renter',
            field=models.ManyToManyField(related_name='currentRenter', to='genie.User'),
        ),
    ]
