# Generated by Django 3.1.7 on 2021-03-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0007_auto_20210316_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('streetAddress', models.CharField(max_length=200)),
                ('city', models.CharField(default='Logan', max_length=200)),
                ('zip', models.CharField(default='84321', max_length=200)),
            ],
        ),
    ]
