# Generated by Django 3.1.7 on 2021-04-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0009_auto_20210405_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='spot',
            field=models.ManyToManyField(related_name='linkedSpot', to='genie.ParkingSpot'),
        ),
    ]
