# Generated by Django 3.1.7 on 2021-04-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0010_auto_20210408_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='code',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
